apiVersion: v1
kind: Service
metadata:
  name: go-web
  labels:
    app: go-web
spec:
  selector:
    app: go-web
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
