alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: "warning-webhook"
      group_by: ["alertname", "severity"]
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 30m

      routes:
        - matchers:
            - severity="critical"
          receiver: "critical-webhook"

    receivers:
      - name: "warning-webhook"
        webhook_configs:
          - url: "http://sink-warning.monitoring.svc.cluster.local/"
            send_resolved: true

      - name: "critical-webhook"
        webhook_configs:
          - url: "http://sink-critical.monitoring.svc.cluster.local/"
            send_resolved: true
