replicaCount: 1

image:
  repository: devops-labs-go
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  APP_PORT: "8080"
  APP_ENV: "dev"

resources: {}
